// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TaskFlow.Infrastructure.Data;

#nullable disable

namespace TaskFlow.Infrastructure.Migrations
{
    [DbContext(typeof(TaskFlowDbContext))]
    partial class TaskFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow.Domain.Models.Activity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Priority")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasDefaultValue("Normal")
                    .HasColumnType("nvarchar(10)");

                b.Property<bool>("IsCompleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");
                b.ToTable("Activities");

                b.HasData(
                    new { Id = 1, Title = "Estudiar Arquitectura de Software", Description = "Repasar patrones GoF y ADRs", Date = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc), Category = "Estudio", Priority = "High", IsCompleted = false, CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 2, Title = "Entregar proyecto TaskFlow", Description = "Subir avances al repositorio", Date = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc), Category = "Universidad", Priority = "High", IsCompleted = false, CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 3, Title = "Hacer ejercicio", Description = "30 min cardio", Date = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc), Category = "Salud", Priority = "Normal", IsCompleted = false, CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc) }
                );
            });

            modelBuilder.Entity("TaskFlow.Domain.Models.Task", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ActivityId")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsCompleted")
                    .HasColumnType("bit");

                b.Property<DateTime?>("DueTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");
                b.HasIndex("ActivityId");
                b.ToTable("Tasks");

                b.HasData(
                    new { Id = 1, ActivityId = 1, Title = "Leer sobre Strategy Pattern", Description = "Capítulo 5 del libro GoF", IsCompleted = true, CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 2, ActivityId = 1, Title = "Implementar Builder en el proyecto", Description = "ActivityBuilder y TaskBuilder", IsCompleted = false, CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc) },
                    new { Id = 3, ActivityId = 2, Title = "Hacer commit de los patrones", Description = "Push a rama api", IsCompleted = false, CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, DateTimeKind.Utc) }
                );
            });

            modelBuilder.Entity("TaskFlow.Domain.Models.Task", b =>
            {
                b.HasOne("TaskFlow.Domain.Models.Activity", "Activity")
                    .WithMany("Tasks")
                    .HasForeignKey("ActivityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Activity");
            });

            modelBuilder.Entity("TaskFlow.Domain.Models.Activity", b =>
            {
                b.Navigation("Tasks");
            });
#pragma warning restore 612, 618
        }
    }
}
